"""Claude-facing entry points for rebuttal and final report generation."""

from __future__ import annotations

from typing import Any


def ask_claude_to_reply(pr_number: int, issues: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return placeholder Claude replies until a live integration is wired."""

    replies = []
    for issue in issues:
        replies.append(
            {
                "issue_id": issue["issue_id"],
                "position": "accept",
                "reason": "Placeholder reply generated by the local scaffold.",
                "action": "pending_manual_patch",
                "patch_commit": "",
                "tests_added": [],
                "residual_risk": "unknown",
            }
        )
    return replies


def ask_claude_for_final_report(
    pr_number: int, codex_round2: list[dict[str, Any]]
) -> dict[str, Any]:
    """Return a placeholder human-facing dispute report."""

    return {
        "pr": pr_number,
        "agreed": 0,
        "partial": 0,
        "disputed": len(codex_round2),
        "disputes": codex_round2,
        "merge_recommendation": "blocked" if codex_round2 else "needs_human_approval",
    }
